# Go Drive Duplicates Configuration
# Google Drive duplicate file finder and manager

# HTTP Server Configuration
server:
  host: localhost
  port: 9090
  read_timeout: 300s   # 5분으로 증가
  write_timeout: 300s  # 5분으로 증가
  idle_timeout: 300s   # 5분으로 증가
  enable_tls: false
  cert_file: ""
  key_file: ""

# Database Configuration
database:
  path: ./drive_duplicates.db
  max_open_conns: 25
  max_idle_conns: 5
  max_lifetime: 1h

# Google Drive API Configuration
google_drive:
  credentials_path: ./credentials.json
  api_key: ""
  scopes:
    - https://www.googleapis.com/auth/drive.readonly
  max_retries: 3
  request_timeout: 300s  # 5분으로 증가

# Hash Calculation Configuration
hash:
  algorithm: sha256
  worker_count: 4
  max_file_size: 1073741824  # 1GB in bytes
  buffer_size: 65536         # 64KB in bytes

# Processing Configuration
processing:
  batch_size: 100
  worker_count: 5
  save_interval: 30s
  max_retries: 3

# Security Configuration
security:
  enable_cors: true
  enable_rate_limit: false
  rate_limit: 100
  allowed_origins:
    - "*"

# Logging Configuration
logging:
  level: info
  format: text
  output: stdout
  max_size: 100    # MB
  max_backups: 3
  max_age: 7       # days
  compress: true

# Environment setting
environment: development