# Development Environment Configuration
# Extended configuration for development environment

server:
  host: localhost
  port: 8080
  read_timeout: 60s     # Longer timeout for debugging
  write_timeout: 60s
  idle_timeout: 120s
  enable_tls: false

database:
  path: ./drive_duplicates_dev.db
  max_open_conns: 10    # Lower for development
  max_idle_conns: 2
  max_lifetime: 30m

google_drive:
  credentials_path: ./credentials.json
  api_key: ""
  scopes:
    - https://www.googleapis.com/auth/drive.readonly
  max_retries: 5        # More retries for development
  request_timeout: 60s  # Longer timeout for debugging

hash:
  algorithm: sha256
  worker_count: 2       # Lower for development
  max_file_size: 1073741824
  buffer_size: 32768    # Smaller buffer for debugging

processing:
  batch_size: 50        # Smaller batches for development
  worker_count: 2
  save_interval: 10s    # More frequent saves
  max_retries: 5

security:
  enable_cors: true
  enable_rate_limit: false  # Disabled for development
  rate_limit: 1000
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:8080"

logging:
  level: debug          # Verbose logging for development
  format: text
  output: stdout
  max_size: 50
  max_backups: 2
  max_age: 3
  compress: false       # No compression for easy reading

environment: development