# Production Environment Configuration
# Optimized configuration for production environment

server:
  host: 0.0.0.0         # Listen on all interfaces
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  enable_tls: true      # Enable TLS in production
  cert_file: /etc/ssl/certs/app.crt
  key_file: /etc/ssl/private/app.key

database:
  path: /var/lib/go-drive-duplicates/drive_duplicates.db
  max_open_conns: 50    # Higher for production load
  max_idle_conns: 10
  max_lifetime: 1h

google_drive:
  credentials_path: /etc/go-drive-duplicates/credentials.json
  api_key: ""
  scopes:
    - https://www.googleapis.com/auth/drive.readonly
  max_retries: 3
  request_timeout: 30s

hash:
  algorithm: sha256
  worker_count: 8       # More workers for production
  max_file_size: 1073741824
  buffer_size: 65536

processing:
  batch_size: 200       # Larger batches for efficiency
  worker_count: 10      # More workers for production
  save_interval: 30s
  max_retries: 3

security:
  enable_cors: true
  enable_rate_limit: true   # Enable rate limiting
  rate_limit: 100
  allowed_origins:
    - "https://yourdomain.com"
    - "https://app.yourdomain.com"

logging:
  level: info           # Less verbose in production
  format: json          # Structured logging for production
  output: /var/log/go-drive-duplicates/app.log
  max_size: 100
  max_backups: 5
  max_age: 30           # Keep logs for 30 days
  compress: true

environment: production